In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'numpy'

In [3]:
df1=pd.read_csv('datafile1.csv',skiprows=20)
df2=pd.read_csv('datafile2.csv',skiprows=17)

In [4]:
df1.head()

,LAT,LON,YEAR,MO,DY,PRECTOT,QV2M,RH2M,PS,T2M_RANGE,TS,T2MDEW,T2MWET,T2M_MAX,T2M_MIN,T2M
0,27.66671,85.35001,2013,1,1,0.00,3.61,43.19,84.00,10.74,5.30,-3.79,-3.60,15.23,4.49,8.72
1,27.66671,85.35001,2013,1,2,0.06,2.88,33.65,84.07,11.65,5.43,-6.77,-6.42,16.82,5.17,9.08
2,27.66671,85.35001,2013,1,3,0.00,2.99,38.91,84.08,10.75,4.72,-6.33,-6.08,14.58,3.84,7.50
3,27.66671,85.35001,2013,1,4,0.00,2.77,36.93,84.09,11.64,3.93,-7.48,-7.12,14.69,3.06,7.12
4,27.66671,85.35001,2013,1,5,0.00,2.37,33.48,83.93,11.96,3.07,-9.67,-9.06,13.81,1.85,6.29

In [5]:
df2.head()

,LAT,LON,YEAR,MO,DY,WS50M_RANGE,WS10M_RANGE,WS50M_MIN,WS10M_MIN,WS50M_MAX,WS10M_MAX,WS50M,WS10M
0,27.66671,85.35001,2013,1,1,2.36,3.35,0.91,0.67,3.27,4.02,1.64,1.61
1,27.66671,85.35001,2013,1,2,1.91,2.64,0.90,0.64,2.82,3.29,1.57,1.47
2,27.66671,85.35001,2013,1,3,2.92,3.33,1.28,1.08,4.20,4.41,2.27,1.99
3,27.66671,85.35001,2013,1,4,2.57,3.26,1.89,1.26,4.46,4.51,2.91,2.38
4,27.66671,85.35001,2013,1,5,1.94,2.69,1.57,1.05,3.51,3.74,2.50,2.08

In [6]:
#merging two csvs
df=df=pd.merge(df1,df2,how='left',on=('LAT','LON','YEAR','MO','DY'))
df.head()

,LAT,LON,YEAR,MO,DY,PRECTOT,QV2M,RH2M,PS,T2M_RANGE,...,T2M_MIN,T2M,WS50M_RANGE,WS10M_RANGE,WS50M_MIN,WS10M_MIN,WS50M_MAX,WS10M_MAX,WS50M,WS10M
0,27.66671,85.35001,2013,1,1,0.00,3.61,43.19,84.00,10.74,...,4.49,8.72,2.36,3.35,0.91,0.67,3.27,4.02,1.64,1.61
1,27.66671,85.35001,2013,1,2,0.06,2.88,33.65,84.07,11.65,...,5.17,9.08,1.91,2.64,0.90,0.64,2.82,3.29,1.57,1.47
2,27.66671,85.35001,2013,1,3,0.00,2.99,38.91,84.08,10.75,...,3.84,7.50,2.92,3.33,1.28,1.08,4.20,4.41,2.27,1.99
3,27.66671,85.35001,2013,1,4,0.00,2.77,36.93,84.09,11.64,...,3.06,7.12,2.57,3.26,1.89,1.26,4.46,4.51,2.91,2.38
4,27.66671,85.35001,2013,1,5,0.00,2.37,33.48,83.93,11.96,...,1.85,6.29,1.94,2.69,1.57,1.05,3.51,3.74,2.50,2.08

In [7]:
df['MO']=df.MO.astype(str)
df['YEAR']=df.YEAR.astype(str)
df['DY']=df.DY.astype(str)

df['date']=df['YEAR'].str.cat(df['MO'],sep='/')
df['Date']=df['date'].str.cat(df['DY'],sep='/')
df.head()

,LAT,LON,YEAR,MO,DY,PRECTOT,QV2M,RH2M,PS,T2M_RANGE,...,WS50M_RANGE,WS10M_RANGE,WS50M_MIN,WS10M_MIN,WS50M_MAX,WS10M_MAX,WS50M,WS10M,date,Date
0,27.66671,85.35001,2013,1,1,0.00,3.61,43.19,84.00,10.74,...,2.36,3.35,0.91,0.67,3.27,4.02,1.64,1.61,2013/1,2013/1/1
1,27.66671,85.35001,2013,1,2,0.06,2.88,33.65,84.07,11.65,...,1.91,2.64,0.90,0.64,2.82,3.29,1.57,1.47,2013/1,2013/1/2
2,27.66671,85.35001,2013,1,3,0.00,2.99,38.91,84.08,10.75,...,2.92,3.33,1.28,1.08,4.20,4.41,2.27,1.99,2013/1,2013/1/3
3,27.66671,85.35001,2013,1,4,0.00,2.77,36.93,84.09,11.64,...,2.57,3.26,1.89,1.26,4.46,4.51,2.91,2.38,2013/1,2013/1/4
4,27.66671,85.35001,2013,1,5,0.00,2.37,33.48,83.93,11.96,...,1.94,2.69,1.57,1.05,3.51,3.74,2.50,2.08,2013/1,2013/1/5

In [8]:
#removing lat and lon columns
df.drop(columns=['YEAR','MO','DY','LAT','LON','QV2M','date','WS50M_RANGE', 'WS50M_MIN','WS50M_MAX', 'WS50M','T2MDEW', 'T2MWET',
       'WS10M_MIN', 'WS10M_MAX','WS10M','TS','T2M','T2M_RANGE'],axis=1,inplace=True)
df.head()

   PRECTOT   RH2M     PS  T2M_MAX  T2M_MIN  WS10M_RANGE      Date
0     0.00  43.19  84.00    15.23     4.49         3.35  2013/1/1
1     0.06  33.65  84.07    16.82     5.17         2.64  2013/1/2
2     0.00  38.91  84.08    14.58     3.84         3.33  2013/1/3
3     0.00  36.93  84.09    14.69     3.06         3.26  2013/1/4
4     0.00  33.48  83.93    13.81     1.85         2.69  2013/1/5

In [9]:
df.set_index(['Date'],inplace=True)
df.head()

          PRECTOT   RH2M     PS  T2M_MAX  T2M_MIN  WS10M_RANGE
Date
2013/1/1     0.00  43.19  84.00    15.23     4.49         3.35
2013/1/2     0.06  33.65  84.07    16.82     5.17         2.64
2013/1/3     0.00  38.91  84.08    14.58     3.84         3.33
2013/1/4     0.00  36.93  84.09    14.69     3.06         3.26
2013/1/5     0.00  33.48  83.93    13.81     1.85         2.69

In [10]:
df.dtypes

PRECTOT        float64
RH2M           float64
PS             float64
T2M_MAX        float64
T2M_MIN        float64
WS10M_RANGE    float64
dtype: object

In [11]:
df.isnull().values.any()

False

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2556 entries, 2013/1/1 to 2019/12/31
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PRECTOT      2556 non-null   float64
 1   RH2M         2556 non-null   float64
 2   PS           2556 non-null   float64
 3   T2M_MAX      2556 non-null   float64
 4   T2M_MIN      2556 non-null   float64
 5   WS10M_RANGE  2556 non-null   float64
dtypes: float64(6)
memory usage: 139.8+ KB

In [13]:
df.tail()

            PRECTOT   RH2M     PS  T2M_MAX  T2M_MIN  WS10M_RANGE
Date
2019/12/27      0.0  54.14  84.01    11.10     0.29         2.62
2019/12/28      0.0  50.06  84.27    12.44    -2.01         2.69
2019/12/29      0.0  44.74  84.33    13.56     3.12         2.42
2019/12/30      0.0  44.56  84.39    13.74     3.24         2.63
2019/12/31      0.0  40.99  84.51    13.63     4.76         2.74

# New Section

In [ ]:
fig,ax=plt.subplots(figsize=(25,25))
for i in range(len(df.columns)):
  plt.subplot(len(df.columns),1,i+1)
  name=df.columns[i]
  plt.plot(df[name])
  plt.title(name,y=0,loc='right')
  plt.yticks([])
plt.show()
fig.tight_layout()

In [ ]:
plt.figure(figsize=(30,5))
df['PRECTOT'].plot()

In [ ]:
df.columns

In [ ]:
df.describe()

In [14]:
from sklearn.preprocessing import MinMaxScaler

In [15]:
scalar=MinMaxScaler()

In [16]:
#scale the data
data_train=df.loc[:'2017/12/31',:][[  'PRECTOT', 'RH2M', 'PS', 'T2M_MAX', 'T2M_MIN', 'WS10M_RANGE']]
data_test=df.loc['2018/1/1':'2019/12/31',:][[  'PRECTOT', 'RH2M', 'PS',  'T2M_MAX', 'T2M_MIN','WS10M_RANGE']]



data_train_scaled=scalar.fit_transform(data_train)
data_test_scaled=scalar.transform(data_test)

In [17]:
#create training and testing dataset
#splitting data into X and Y for training  
x_train,y_train=[],[]
for i in range(1,len(data_train_scaled)):
  x_train.append(data_train_scaled[i-1])
  y_train.append(data_train_scaled[i])


#splitting data into X and Y for testing
x_test=[]
y_test=[]
for i in range(1,len(data_test_scaled)):
  x_test.append(data_test_scaled[i-1])
  y_test.append(data_test_scaled[i])

In [18]:
pd.DataFrame(y_train)

             0         1         2         3         4         5
0     0.001041  0.246827  0.629213  0.323835  0.313590  0.187959
1     0.000000  0.308068  0.634831  0.222524  0.252525  0.289280
2     0.000000  0.285016  0.640449  0.227499  0.216713  0.279001
3     0.000000  0.244848  0.550562  0.187698  0.161157  0.195301
4     0.000000  0.182792  0.589888  0.137494  0.101010  0.165932
...        ...       ...       ...       ...       ...       ...
1820  0.000000  0.283269  0.780899  0.408412  0.346648  0.214391
1821  0.000000  0.230411  0.786517  0.400724  0.472452  0.199706
1822  0.000000  0.228781  0.825843  0.417006  0.443985  0.207048
1823  0.000000  0.244732  0.814607  0.398915  0.435721  0.350954
1824  0.000000  0.284666  0.724719  0.347354  0.388430  0.187959

[1825 rows x 6 columns]

In [19]:
x_train,y_train=np.array(x_train),np.array(y_train)
x_train.shape,y_train.shape

((1825, 6), (1825, 6))

In [20]:
x_test=np.array(x_test)
y_test=np.array(y_test)
x_test.shape

(729, 6)

In [21]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import Adam
from keras.models import load_model
from keras.layers import Dropout

In [22]:
model = Sequential()
model.add(Dense(20, input_dim=6, activation='sigmoid'))
model.add(Dense(20, activation='sigmoid'))
model.add(Dense(6))


model.summary()


model.compile(optimizer='adam',loss='mse', metrics=['accuracy'])

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 20)                140
_________________________________________________________________
dense_1 (Dense)              (None, 20)                420
_________________________________________________________________
dense_2 (Dense)              (None, 6)                 126
=================================================================
Total params: 686
Trainable params: 686
Non-trainable params: 0
_________________________________________________________________

In [20]:
history=model.fit(x_train,y_train,validation_data=(x_test,y_test) ,epochs=150,batch_size=15,shuffle=False)

Epoch 1/150
122/122 [==============================] - 0s 2ms/step - loss: 0.0992 - accuracy: 0.2532 - val_loss: 0.0378 - val_accuracy: 0.3059
Epoch 2/150
122/122 [==============================] - 0s 817us/step - loss: 0.0417 - accuracy: 0.3025 - val_loss: 0.0369 - val_accuracy: 0.3059
Epoch 3/150
122/122 [==============================] - 0s 924us/step - loss: 0.0409 - accuracy: 0.3025 - val_loss: 0.0358 - val_accuracy: 0.3059
Epoch 4/150
122/122 [==============================] - 0s 899us/step - loss: 0.0398 - accuracy: 0.3025 - val_loss: 0.0345 - val_accuracy: 0.3059
Epoch 5/150
122/122 [==============================] - 0s 916us/step - loss: 0.0385 - accuracy: 0.3036 - val_loss: 0.0331 - val_accuracy: 0.3059
Epoch 6/150
122/122 [==============================] - 0s 907us/step - loss: 0.0370 - accuracy: 0.3041 - val_loss: 0.0315 - val_accuracy: 0.3059
Epoch 7/150
122/122 [==============================] - 0s 842us/step - loss: 0.0353 - accuracy: 0.3140 - val_loss: 0.0298 - val_accuracy: 0.3059
Epoch 8/150
122/122 [==============================] - 0s 826us/step - loss: 0.0334 - accuracy: 0.3386 - val_loss: 0.0279 - val_accuracy: 0.3237
Epoch 9/150
122/122 [==============================] - 0s 785us/step - loss: 0.0313 - accuracy: 0.4000 - val_loss: 0.0258 - val_accuracy: 0.4060
Epoch 10/150
122/122 [==============================] - 0s 817us/step - loss: 0.0291 - accuracy: 0.4778 - val_loss: 0.0236 - val_accuracy: 0.4691
Epoch 11/150
122/122 [==============================] - 0s 809us/step - loss: 0.0267 - accuracy: 0.5419 - val_loss: 0.0214 - val_accuracy: 0.5267
Epoch 12/150
122/122 [==============================] - 0s 793us/step - loss: 0.0243 - accuracy: 0.5874 - val_loss: 0.0193 - val_accuracy: 0.5748
Epoch 13/150
122/122 [==============================] - 0s 768us/step - loss: 0.0220 - accuracy: 0.6137 - val_loss: 0.0173 - val_accuracy: 0.6077
Epoch 14/150
122/122 [==============================] - 0s 801us/step - loss: 0.0199 - accuracy: 0.6329 - val_loss: 0.0155 - val_accuracy: 0.6433
Epoch 15/150
122/122 [==============================] - 0s 760us/step - loss: 0.0180 - accuracy: 0.6455 - val_loss: 0.0140 - val_accuracy: 0.6516
Epoch 16/150
122/122 [==============================] - 0s 769us/step - loss: 0.0164 - accuracy: 0.6542 - val_loss: 0.0128 - val_accuracy: 0.6653
Epoch 17/150
122/122 [==============================] - 0s 809us/step - loss: 0.0150 - accuracy: 0.6592 - val_loss: 0.0119 - val_accuracy: 0.6680
Epoch 18/150
122/122 [==============================] - 0s 801us/step - loss: 0.0139 - accuracy: 0.6658 - val_loss: 0.0112 - val_accuracy: 0.6776
Epoch 19/150
122/122 [==============================] - 0s 752us/step - loss: 0.0130 - accuracy: 0.6685 - val_loss: 0.0106 - val_accuracy: 0.6927
Epoch 20/150
122/122 [==============================] - 0s 777us/step - loss: 0.0122 - accuracy: 0.6729 - val_loss: 0.0101 - val_accuracy: 0.6996
Epoch 21/150
122/122 [==============================] - 0s 842us/step - loss: 0.0115 - accuracy: 0.6756 - val_loss: 0.0096 - val_accuracy: 0.7078
Epoch 22/150
122/122 [==============================] - 0s 768us/step - loss: 0.0108 - accuracy: 0.6855 - val_loss: 0.0092 - val_accuracy: 0.7243
Epoch 23/150
122/122 [==============================] - 0s 809us/step - loss: 0.0101 - accuracy: 0.6970 - val_loss: 0.0088 - val_accuracy: 0.7421
Epoch 24/150
122/122 [==============================] - 0s 817us/step - loss: 0.0096 - accuracy: 0.7156 - val_loss: 0.0085 - val_accuracy: 0.7503
Epoch 25/150
122/122 [==============================] - 0s 793us/step - loss: 0.0091 - accuracy: 0.7299 - val_loss: 0.0083 - val_accuracy: 0.7517
Epoch 26/150
122/122 [==============================] - 0s 785us/step - loss: 0.0086 - accuracy: 0.7425 - val_loss: 0.0081 - val_accuracy: 0.7613
Epoch 27/150
122/122 [==============================] - 0s 834us/step - loss: 0.0083 - accuracy: 0.7595 - val_loss: 0.0079 - val_accuracy: 0.7709
Epoch 28/150
122/122 [==============================] - 0s 801us/step - loss: 0.0080 - accuracy: 0.7721 - val_loss: 0.0078 - val_accuracy: 0.7737
Epoch 29/150
122/122 [==============================] - 0s 826us/step - loss: 0.0078 - accuracy: 0.7879 - val_loss: 0.0077 - val_accuracy: 0.7874
Epoch 30/150
122/122 [==============================] - 0s 801us/step - loss: 0.0077 - accuracy: 0.7995 - val_loss: 0.0076 - val_accuracy: 0.7915
Epoch 31/150
122/122 [==============================] - 0s 817us/step - loss: 0.0076 - accuracy: 0.8049 - val_loss: 0.0076 - val_accuracy: 0.7901
Epoch 32/150
122/122 [==============================] - 0s 834us/step - loss: 0.0075 - accuracy: 0.8071 - val_loss: 0.0075 - val_accuracy: 0.7956
Epoch 33/150
122/122 [==============================] - 0s 801us/step - loss: 0.0074 - accuracy: 0.8099 - val_loss: 0.0075 - val_accuracy: 0.8011
Epoch 34/150
122/122 [==============================] - 0s 809us/step - loss: 0.0074 - accuracy: 0.8132 - val_loss: 0.0074 - val_accuracy: 0.7984
Epoch 35/150
122/122 [==============================] - 0s 817us/step - loss: 0.0073 - accuracy: 0.8115 - val_loss: 0.0074 - val_accuracy: 0.7984
Epoch 36/150
122/122 [==============================] - 0s 826us/step - loss: 0.0073 - accuracy: 0.8093 - val_loss: 0.0073 - val_accuracy: 0.7984
Epoch 37/150
122/122 [==============================] - 0s 875us/step - loss: 0.0072 - accuracy: 0.8099 - val_loss: 0.0073 - val_accuracy: 0.7984
Epoch 38/150
122/122 [==============================] - 0s 1ms/step - loss: 0.0072 - accuracy: 0.8104 - val_loss: 0.0072 - val_accuracy: 0.7984
Epoch 39/150
122/122 [==============================] - 0s 940us/step - loss: 0.0071 - accuracy: 0.8093 - val_loss: 0.0071 - val_accuracy: 0.7956
Epoch 40/150
122/122 [==============================] - 0s 809us/step - loss: 0.0071 - accuracy: 0.8099 - val_loss: 0.0071 - val_accuracy: 0.7956
Epoch 41/150
122/122 [==============================] - 0s 777us/step - loss: 0.0070 - accuracy: 0.8115 - val_loss: 0.0070 - val_accuracy: 0.7956
Epoch 42/150
122/122 [==============================] - 0s 785us/step - loss: 0.0070 - accuracy: 0.8126 - val_loss: 0.0070 - val_accuracy: 0.7956
Epoch 43/150
122/122 [==============================] - 0s 760us/step - loss: 0.0069 - accuracy: 0.8137 - val_loss: 0.0069 - val_accuracy: 0.7984
Epoch 44/150
122/122 [==============================] - 0s 809us/step - loss: 0.0068 - accuracy: 0.8153 - val_loss: 0.0068 - val_accuracy: 0.7997
Epoch 45/150
122/122 [==============================] - 0s 785us/step - loss: 0.0068 - accuracy: 0.8153 - val_loss: 0.0068 - val_accuracy: 0.8011
Epoch 46/150
122/122 [==============================] - 0s 752us/step - loss: 0.0067 - accuracy: 0.8153 - val_loss: 0.0067 - val_accuracy: 0.8011
Epoch 47/150
122/122 [==============================] - 0s 817us/step - loss: 0.0067 - accuracy: 0.8159 - val_loss: 0.0066 - val_accuracy: 0.8025
Epoch 48/150
122/122 [==============================] - 0s 785us/step - loss: 0.0066 - accuracy: 0.8181 - val_loss: 0.0066 - val_accuracy: 0.8052
Epoch 49/150
122/122 [==============================] - 0s 899us/step - loss: 0.0066 - accuracy: 0.8181 - val_loss: 0.0065 - val_accuracy: 0.8066
Epoch 50/150
122/122 [==============================] - 0s 883us/step - loss: 0.0065 - accuracy: 0.8181 - val_loss: 0.0065 - val_accuracy: 0.8080
Epoch 51/150
122/122 [==============================] - 0s 940us/step - loss: 0.0065 - accuracy: 0.8192 - val_loss: 0.0064 - val_accuracy: 0.8066
Epoch 52/150
122/122 [==============================] - 0s 826us/step - loss: 0.0064 - accuracy: 0.8197 - val_loss: 0.0063 - val_accuracy: 0.8080
Epoch 53/150
122/122 [==============================] - 0s 965us/step - loss: 0.0064 - accuracy: 0.8203 - val_loss: 0.0063 - val_accuracy: 0.8093
Epoch 54/150
122/122 [==============================] - 0s 932us/step - loss: 0.0063 - accuracy: 0.8208 - val_loss: 0.0062 - val_accuracy: 0.8107
Epoch 55/150
122/122 [==============================] - 0s 875us/step - loss: 0.0063 - accuracy: 0.8192 - val_loss: 0.0062 - val_accuracy: 0.8093
Epoch 56/150
122/122 [==============================] - 0s 1ms/step - loss: 0.0062 - accuracy: 0.8197 - val_loss: 0.0061 - val_accuracy: 0.8107
Epoch 57/150
122/122 [==============================] - 0s 1ms/step - loss: 0.0062 - accuracy: 0.8203 - val_loss: 0.0061 - val_accuracy: 0.8107
Epoch 58/150
122/122 [==============================] - 0s 973us/step - loss: 0.0062 - accuracy: 0.8214 - val_loss: 0.0061 - val_accuracy: 0.8107
Epoch 59/150
122/122 [==============================] - 0s 997us/step - loss: 0.0061 - accuracy: 0.8219 - val_loss: 0.0060 - val_accuracy: 0.8107
Epoch 60/150
122/122 [==============================] - 0s 883us/step - loss: 0.0061 - accuracy: 0.8225 - val_loss: 0.0060 - val_accuracy: 0.8093
Epoch 61/150
122/122 [==============================] - 0s 768us/step - loss: 0.0061 - accuracy: 0.8230 - val_loss: 0.0059 - val_accuracy: 0.8107
Epoch 62/150
122/122 [==============================] - 0s 850us/step - loss: 0.0060 - accuracy: 0.8241 - val_loss: 0.0059 - val_accuracy: 0.8107
Epoch 63/150
122/122 [==============================] - 0s 785us/step - loss: 0.0060 - accuracy: 0.8247 - val_loss: 0.0059 - val_accuracy: 0.8134
Epoch 64/150
122/122 [==============================] - 0s 785us/step - loss: 0.0060 - accuracy: 0.8236 - val_loss: 0.0058 - val_accuracy: 0.8134
Epoch 65/150
122/122 [==============================] - 0s 777us/step - loss: 0.0059 - accuracy: 0.8241 - val_loss: 0.0058 - val_accuracy: 0.8162
Epoch 66/150
122/122 [==============================] - 0s 752us/step - loss: 0.0059 - accuracy: 0.8241 - val_loss: 0.0058 - val_accuracy: 0.8093
Epoch 67/150
122/122 [==============================] - 0s 744us/step - loss: 0.0059 - accuracy: 0.8236 - val_loss: 0.0058 - val_accuracy: 0.8093
Epoch 68/150
122/122 [==============================] - 0s 760us/step - loss: 0.0059 - accuracy: 0.8230 - val_loss: 0.0057 - val_accuracy: 0.8107
Epoch 69/150
122/122 [==============================] - 0s 785us/step - loss: 0.0059 - accuracy: 0.8258 - val_loss: 0.0057 - val_accuracy: 0.8093
Epoch 70/150
122/122 [==============================] - 0s 768us/step - loss: 0.0059 - accuracy: 0.8164 - val_loss: 0.0058 - val_accuracy: 0.8038
Epoch 71/150
122/122 [==============================] - 0s 760us/step - loss: 0.0060 - accuracy: 0.8170 - val_loss: 0.0060 - val_accuracy: 0.8025
Epoch 72/150
122/122 [==============================] - 0s 744us/step - loss: 0.0060 - accuracy: 0.8263 - val_loss: 0.0068 - val_accuracy: 0.7737
Epoch 73/150
122/122 [==============================] - 0s 785us/step - loss: 0.0077 - accuracy: 0.7649 - val_loss: 0.0083 - val_accuracy: 0.7586
Epoch 74/150
122/122 [==============================] - 0s 736us/step - loss: 0.0076 - accuracy: 0.7962 - val_loss: 0.0059 - val_accuracy: 0.7984
Epoch 75/150
122/122 [==============================] - 0s 768us/step - loss: 0.0059 - accuracy: 0.8247 - val_loss: 0.0056 - val_accuracy: 0.8025
Epoch 76/150
122/122 [==============================] - 0s 760us/step - loss: 0.0057 - accuracy: 0.8279 - val_loss: 0.0056 - val_accuracy: 0.8107
Epoch 77/150
122/122 [==============================] - 0s 744us/step - loss: 0.0057 - accuracy: 0.8258 - val_loss: 0.0056 - val_accuracy: 0.8080
Epoch 78/150
122/122 [==============================] - 0s 752us/step - loss: 0.0057 - accuracy: 0.8279 - val_loss: 0.0056 - val_accuracy: 0.8066
Epoch 79/150
122/122 [==============================] - 0s 752us/step - loss: 0.0057 - accuracy: 0.8268 - val_loss: 0.0056 - val_accuracy: 0.8066
Epoch 80/150
122/122 [==============================] - 0s 768us/step - loss: 0.0057 - accuracy: 0.8268 - val_loss: 0.0055 - val_accuracy: 0.8066
Epoch 81/150
122/122 [==============================] - 0s 793us/step - loss: 0.0057 - accuracy: 0.8274 - val_loss: 0.0055 - val_accuracy: 0.8080
Epoch 82/150
122/122 [==============================] - 0s 793us/step - loss: 0.0057 - accuracy: 0.8268 - val_loss: 0.0055 - val_accuracy: 0.8093
Epoch 83/150
122/122 [==============================] - 0s 785us/step - loss: 0.0057 - accuracy: 0.8279 - val_loss: 0.0055 - val_accuracy: 0.8066
Epoch 84/150
122/122 [==============================] - 0s 752us/step - loss: 0.0057 - accuracy: 0.8274 - val_loss: 0.0055 - val_accuracy: 0.8080
Epoch 85/150
122/122 [==============================] - 0s 785us/step - loss: 0.0057 - accuracy: 0.8296 - val_loss: 0.0055 - val_accuracy: 0.8080
Epoch 86/150
122/122 [==============================] - 0s 744us/step - loss: 0.0057 - accuracy: 0.8285 - val_loss: 0.0055 - val_accuracy: 0.8080
Epoch 87/150
122/122 [==============================] - 0s 777us/step - loss: 0.0057 - accuracy: 0.8290 - val_loss: 0.0055 - val_accuracy: 0.8080
Epoch 88/150
122/122 [==============================] - 0s 760us/step - loss: 0.0057 - accuracy: 0.8268 - val_loss: 0.0055 - val_accuracy: 0.8080
Epoch 89/150
122/122 [==============================] - 0s 777us/step - loss: 0.0057 - accuracy: 0.8252 - val_loss: 0.0055 - val_accuracy: 0.8093
Epoch 90/150
122/122 [==============================] - 0s 752us/step - loss: 0.0057 - accuracy: 0.8268 - val_loss: 0.0055 - val_accuracy: 0.8134
Epoch 91/150
122/122 [==============================] - 0s 883us/step - loss: 0.0057 - accuracy: 0.8296 - val_loss: 0.0055 - val_accuracy: 0.8093
Epoch 92/150
122/122 [==============================] - 0s 850us/step - loss: 0.0058 - accuracy: 0.8192 - val_loss: 0.0056 - val_accuracy: 0.8066
Epoch 93/150
122/122 [==============================] - 0s 900us/step - loss: 0.0063 - accuracy: 0.8104 - val_loss: 0.0060 - val_accuracy: 0.8203
Epoch 94/150
122/122 [==============================] - 0s 875us/step - loss: 0.0069 - accuracy: 0.8104 - val_loss: 0.0059 - val_accuracy: 0.8066
Epoch 95/150
122/122 [==============================] - 0s 899us/step - loss: 0.0068 - accuracy: 0.8082 - val_loss: 0.0058 - val_accuracy: 0.8080
Epoch 96/150
122/122 [==============================] - 0s 899us/step - loss: 0.0059 - accuracy: 0.8219 - val_loss: 0.0053 - val_accuracy: 0.8121
Epoch 97/150
122/122 [==============================] - 0s 932us/step - loss: 0.0056 - accuracy: 0.8252 - val_loss: 0.0054 - val_accuracy: 0.8080
Epoch 98/150
122/122 [==============================] - 0s 899us/step - loss: 0.0056 - accuracy: 0.8258 - val_loss: 0.0054 - val_accuracy: 0.8107
Epoch 99/150
122/122 [==============================] - 0s 949us/step - loss: 0.0056 - accuracy: 0.8279 - val_loss: 0.0054 - val_accuracy: 0.8080
Epoch 100/150
122/122 [==============================] - 0s 883us/step - loss: 0.0056 - accuracy: 0.8236 - val_loss: 0.0054 - val_accuracy: 0.8107
Epoch 101/150
122/122 [==============================] - 0s 858us/step - loss: 0.0056 - accuracy: 0.8285 - val_loss: 0.0053 - val_accuracy: 0.8080
Epoch 102/150
122/122 [==============================] - 0s 883us/step - loss: 0.0056 - accuracy: 0.8258 - val_loss: 0.0054 - val_accuracy: 0.8093
Epoch 103/150
122/122 [==============================] - 0s 842us/step - loss: 0.0056 - accuracy: 0.8274 - val_loss: 0.0053 - val_accuracy: 0.8093
Epoch 104/150
122/122 [==============================] - 0s 858us/step - loss: 0.0056 - accuracy: 0.8263 - val_loss: 0.0053 - val_accuracy: 0.8093
Epoch 105/150
122/122 [==============================] - 0s 867us/step - loss: 0.0056 - accuracy: 0.8285 - val_loss: 0.0053 - val_accuracy: 0.8093
Epoch 106/150
122/122 [==============================] - 0s 850us/step - loss: 0.0056 - accuracy: 0.8279 - val_loss: 0.0053 - val_accuracy: 0.8093
Epoch 107/150
122/122 [==============================] - 0s 883us/step - loss: 0.0056 - accuracy: 0.8252 - val_loss: 0.0053 - val_accuracy: 0.8107
Epoch 108/150
122/122 [==============================] - 0s 850us/step - loss: 0.0056 - accuracy: 0.8258 - val_loss: 0.0053 - val_accuracy: 0.8107
Epoch 109/150
122/122 [==============================] - 0s 842us/step - loss: 0.0055 - accuracy: 0.8247 - val_loss: 0.0053 - val_accuracy: 0.8093
Epoch 110/150
122/122 [==============================] - 0s 842us/step - loss: 0.0055 - accuracy: 0.8258 - val_loss: 0.0053 - val_accuracy: 0.8107
Epoch 111/150
122/122 [==============================] - 0s 866us/step - loss: 0.0056 - accuracy: 0.8230 - val_loss: 0.0054 - val_accuracy: 0.8121
Epoch 112/150
122/122 [==============================] - 0s 858us/step - loss: 0.0056 - accuracy: 0.8318 - val_loss: 0.0055 - val_accuracy: 0.8134
Epoch 113/150

122/122 [==============================] - 0s 817us/step - loss: 0.0060 - accuracy: 0.8153 - val_loss: 0.0056 - val_accuracy: 0.8107
Epoch 114/150
122/122 [==============================] - 0s 785us/step - loss: 0.0069 - accuracy: 0.8082 - val_loss: 0.0059 - val_accuracy: 0.8134
Epoch 115/150
122/122 [==============================] - 0s 768us/step - loss: 0.0066 - accuracy: 0.8203 - val_loss: 0.0054 - val_accuracy: 0.8080
Epoch 116/150
122/122 [==============================] - 0s 777us/step - loss: 0.0057 - accuracy: 0.8181 - val_loss: 0.0054 - val_accuracy: 0.8121
Epoch 117/150
122/122 [==============================] - 0s 760us/step - loss: 0.0056 - accuracy: 0.8274 - val_loss: 0.0052 - val_accuracy: 0.8107
Epoch 118/150
122/122 [==============================] - 0s 785us/step - loss: 0.0055 - accuracy: 0.8263 - val_loss: 0.0053 - val_accuracy: 0.8121
Epoch 119/150
122/122 [==============================] - 0s 793us/step - loss: 0.0055 - accuracy: 0.8279 - val_loss: 0.0052 - val_accuracy: 0.8121
Epoch 120/150
122/122 [==============================] - 0s 785us/step - loss: 0.0055 - accuracy: 0.8241 - val_loss: 0.0053 - val_accuracy: 0.8121
Epoch 121/150
122/122 [==============================] - 0s 760us/step - loss: 0.0055 - accuracy: 0.8252 - val_loss: 0.0052 - val_accuracy: 0.8093
Epoch 122/150
122/122 [==============================] - 0s 728us/step - loss: 0.0055 - accuracy: 0.8268 - val_loss: 0.0052 - val_accuracy: 0.8121
Epoch 123/150
122/122 [==============================] - 0s 719us/step - loss: 0.0055 - accuracy: 0.8279 - val_loss: 0.0052 - val_accuracy: 0.8121
Epoch 124/150
122/122 [==============================] - 0s 736us/step - loss: 0.0055 - accuracy: 0.8279 - val_loss: 0.0052 - val_accuracy: 0.8107
Epoch 125/150
122/122 [==============================] - 0s 752us/step - loss: 0.0055 - accuracy: 0.8268 - val_loss: 0.0053 - val_accuracy: 0.8121
Epoch 126/150
122/122 [==============================] - 0s 728us/step - loss: 0.0055 - accuracy: 0.8301 - val_loss: 0.0052 - val_accuracy: 0.8134
Epoch 127/150
122/122 [==============================] - 0s 752us/step - loss: 0.0055 - accuracy: 0.8258 - val_loss: 0.0052 - val_accuracy: 0.8093
Epoch 128/150
122/122 [==============================] - 0s 736us/step - loss: 0.0055 - accuracy: 0.8208 - val_loss: 0.0054 - val_accuracy: 0.8134
Epoch 129/150
122/122 [==============================] - 0s 777us/step - loss: 0.0056 - accuracy: 0.8318 - val_loss: 0.0054 - val_accuracy: 0.8148
Epoch 130/150
122/122 [==============================] - 0s 761us/step - loss: 0.0059 - accuracy: 0.8181 - val_loss: 0.0057 - val_accuracy: 0.8121
Epoch 131/150
122/122 [==============================] - 0s 719us/step - loss: 0.0065 - accuracy: 0.8181 - val_loss: 0.0057 - val_accuracy: 0.8134
Epoch 132/150
122/122 [==============================] - 0s 768us/step - loss: 0.0061 - accuracy: 0.8230 - val_loss: 0.0055 - val_accuracy: 0.8093
Epoch 133/150
122/122 [==============================] - 0s 891us/step - loss: 0.0057 - accuracy: 0.8208 - val_loss: 0.0053 - val_accuracy: 0.8162
Epoch 134/150
122/122 [==============================] - 0s 891us/step - loss: 0.0055 - accuracy: 0.8285 - val_loss: 0.0052 - val_accuracy: 0.8080
Epoch 135/150
122/122 [==============================] - 0s 826us/step - loss: 0.0054 - accuracy: 0.8241 - val_loss: 0.0052 - val_accuracy: 0.8134
Epoch 136/150
122/122 [==============================] - 0s 793us/step - loss: 0.0054 - accuracy: 0.8252 - val_loss: 0.0052 - val_accuracy: 0.8107
Epoch 137/150
122/122 [==============================] - 0s 867us/step - loss: 0.0054 - accuracy: 0.8252 - val_loss: 0.0052 - val_accuracy: 0.8134
Epoch 138/150
122/122 [==============================] - 0s 899us/step - loss: 0.0054 - accuracy: 0.8258 - val_loss: 0.0052 - val_accuracy: 0.8107
Epoch 139/150
122/122 [==============================] - 0s 834us/step - loss: 0.0054 - accuracy: 0.8258 - val_loss: 0.0052 - val_accuracy: 0.8107
Epoch 140/150
122/122 [==============================] - 0s 752us/step - loss: 0.0054 - accuracy: 0.8279 - val_loss: 0.0052 - val_accuracy: 0.8134
Epoch 141/150
122/122 [==============================] - 0s 768us/step - loss: 0.0054 - accuracy: 0.8263 - val_loss: 0.0052 - val_accuracy: 0.8107
Epoch 142/150
122/122 [==============================] - 0s 801us/step - loss: 0.0055 - accuracy: 0.8241 - val_loss: 0.0052 - val_accuracy: 0.8176
Epoch 143/150
122/122 [==============================] - 0s 785us/step - loss: 0.0055 - accuracy: 0.8268 - val_loss: 0.0053 - val_accuracy: 0.8107
Epoch 144/150
122/122 [==============================] - 0s 817us/step - loss: 0.0056 - accuracy: 0.8181 - val_loss: 0.0058 - val_accuracy: 0.8052
Epoch 145/150
122/122 [==============================] - 0s 777us/step - loss: 0.0061 - accuracy: 0.8241 - val_loss: 0.0059 - val_accuracy: 0.8093
Epoch 146/150
122/122 [==============================] - 0s 761us/step - loss: 0.0060 - accuracy: 0.8197 - val_loss: 0.0059 - val_accuracy: 0.8080
Epoch 147/150
122/122 [==============================] - 0s 801us/step - loss: 0.0059 - accuracy: 0.8214 - val_loss: 0.0052 - val_accuracy: 0.8134
Epoch 148/150
122/122 [==============================] - 0s 744us/step - loss: 0.0055 - accuracy: 0.8285 - val_loss: 0.0053 - val_accuracy: 0.8066
Epoch 149/150
122/122 [==============================] - 0s 760us/step - loss: 0.0055 - accuracy: 0.8290 - val_loss: 0.0051 - val_accuracy: 0.8080
Epoch 150/150
122/122 [==============================] - 0s 736us/step - loss: 0.0054 - accuracy: 0.8268 - val_loss: 0.0052 - val_accuracy: 0.8080

In [21]:
# save model and architecture to single file
model.save("model222.h5")
print("Saved model to disk")

Saved model to disk

In [23]:
model = load_model('model222.h5')
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 20)                140
_________________________________________________________________
dense_1 (Dense)              (None, 20)                420
_________________________________________________________________
dense_2 (Dense)              (None, 6)                 126
=================================================================
Total params: 686
Trainable params: 686
Non-trainable params: 0
_________________________________________________________________

In [24]:
ans=model.predict(x_test,batch_size=15)
ans=scalar.inverse_transform(ans)
actual_value=scalar.inverse_transform(y_test)

In [24]:
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Training and Validation accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend(['train', 'val'], loc='upper left')
plt.show()

NameError: name 'history' is not defined

In [25]:
scores = model.evaluate(actual_value,ans,verbose=0)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

accuracy: 86.42%

In [26]:
print('actual value')
print(' RH2M   PS  T2M_RANGE T2M_MAX T2M_MIN WS10M_RANGE')

print(pd.DataFrame(actual_value))
print('predicted value')
print(' PRECTOT RH2M PS T2M_RANGE T2M_MAX T2M_MIN T2M WS10M_RANGE')

print(pd.DataFrame(ans))

actual value
 RH2M   PS  T2M_RANGE T2M_MAX T2M_MIN WS10M_RANGE
       0      1      2      3     4     5
0    0.0  47.02  83.91  14.43  4.05  2.75
1    0.0  46.43  83.90  14.63  2.87  3.58
2    0.0  43.62  84.08  15.24  4.32  3.50
3    0.0  42.26  83.95  13.50  2.91  3.85
4    0.0  40.81  83.80  13.47  2.61  3.56
..   ...    ...    ...    ...   ...   ...
724  0.0  54.14  84.01  11.10  0.29  2.62
725  0.0  50.06  84.27  12.44 -2.01  2.69
726  0.0  44.74  84.33  13.56  3.12  2.42
727  0.0  44.56  84.39  13.74  3.24  2.63
728  0.0  40.99  84.51  13.63  4.76  2.74

[729 rows x 6 columns]
predicted value
 PRECTOT RH2M PS T2M_RANGE T2M_MAX T2M_MIN T2M WS10M_RANGE
            0          1          2          3         4         5
0   -0.848998  42.596260  84.135658  16.603422  5.291943  3.673686
1   -0.577767  46.604271  84.062454  14.800923  3.883410  3.571388
2   -0.668408  43.986977  84.035561  14.781254  3.211802  3.892683
3   -0.941887  43.209297  84.163864  15.732800  4.222053  3.754042
4   -0.829611  41.250553  84.061638  14.398915  2.454401  3.948342
..        ...        ...        ...        ...       ...       ...
724 -0.784883  48.845325  84.173958  12.327225  1.551542  3.228203
725 -0.620410  50.457413  84.117432  11.502496  0.722832  3.275125
726 -0.777541  45.333153  84.257149  11.751032  0.304094  3.199656
727 -1.128327  45.619370  84.330803  14.065031  3.133917  3.120215
728 -1.225022  45.401070  84.364006  14.274556  3.273494  3.149885

[729 rows x 6 columns]

In [29]:
66
a=input('Enter the date of day whose weather you would like to predict ')
print('Enter the weather parameters of previous day')
a=[]
print('Precipitation , Relative humidity, Surface pressure , MAX temp ,MIN_temp ,Wind speed at 10M' )
#Precipitation , Relative humidity, Surface pressure , Temperature range, MAX temp ,MIN_temp ,Temperature ,Wind speed at 10M 
for i in range(0,6):
 a.append(float(input()))
a=np.array(a) 
a.shape=(1,6)
#a=pd.DataFrame(a)

#print(a)
print('The entered  weather parameters are :\n')
print('Precipitation=', a[0,0],'mm' ,'\n Relative humidity=',a[0,1],'%', '\n Surface pressure=',a[0,2],'kPa' , '\n MAX temp=',a[0,3],'C',  '\n MIN_temp=',a[0,4],'C' , '\n Wind speed at 10M=',a[0,5] ,'m/s\n\n\n')

a=scalar.transform(a)

ans1=model.predict(a)
ans2=scalar.inverse_transform(ans1)
print('The predicted weather parameters are :\n')
print('Precipitation=', ans2[0,0],'mm' ,'\n Relative humidity=',ans2[0,1],'%', '\n Surface pressure=',ans2[0,2],'kPa' , '\n MAX temp=',ans2[0,3],'C',  '\n MIN_temp=',ans2[0,4],'C' , '\n Wind speed at 10M=',ans2[0,5] ,'m/s')
#print(ans2)

Enter the date of day whose weather you would like to predict 2020/1/1
Enter the weather parameters of previous day
Precipitation , Relative humidity, Surface pressure , MAX temp ,MIN_temp ,Wind speed at 10M
0
53.62
84.67
11.67
5.12
1.1
The entered  weather parameters are :

Precipitation= 0.0 mm
 Relative humidity= 53.62 %
 Surface pressure= 84.67 kPa
 MAX temp= 11.67 C
 MIN_temp= 5.12 C
 Wind speed at 10M= 1.1 m/s



The predicted weather parameters are :

Precipitation= -1.7850426 mm
 Relative humidity= 55.700047 %
 Surface pressure= 84.52854 kPa
 MAX temp= 13.306257 C
 MIN_temp= 3.8064487 C
 Wind speed at 10M= 2.3527853 m/s